meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: jackrabbit_z1
    instances: 1
    networks:
      - name: jackrabbit1

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: jackrabbit1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
