meta:
  environment: ~
  port: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: jackrabbit_z1
    template: jackrabbit
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties:
      jackrabbit:
        port: (( meta.port ))


networks: (( merge ))

properties: {}
